project:
  title: "test"
  type: website  ### 이거 빠지면 안됌
  output-dir: docs
  
  
  
website:
  title: "IAM Powerhouse @ KAIST"
  favicon: "./img/analysis.png"
  open-graph: true
  twitter-card: true
  site-url: https://github.com/GCAM-KAIST
  repo-url: https://github.com/GCAM-KAIST
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About us
      - href: documentation.qmd
        text: Documentation
      - href: gcam_transportation.qmd
        text: GCAM-KAIST7
      - href: blog.qmd
        text: Publications
        
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Twitter
      - icon: github
        href: https://github.com/GCAM-KAIST
        aria-label: GitHub
  
  sidebar:
    style: docked
    contents: 
      - section: "PPT"
        contents:
          - href: intro_slide.qmd
            text: "소개"
          - href: quarto_slideshow.qmd
            text: "Quarto 슬라이드"
      
  
  
editor: visual

