---
title: "IAM KAIST TEAM"
description: "IAM KAIST"
date: today # 날짜 설정: now, last-modified
author:
  - name: IAM KAIST team 
  #  url: 
    affiliation: KAIST
    #affiliation-url: 
title-block-banner: false
#title-block-banner: "#562457"
format:
  html:
    code-fold: true
    toc: true
    toc-depth: 2
    toc-title: 목차
    number-sections: true
    highlight-style: github    
    self-contained: false
link-citation: true
csl: apa-single-spaced.csl
reference-location: margin
---
# Integrated Assessmenent Model(IAM)

Integrated assessment modelling (IAM) is a term used for a type of scientific modelling that tries to link main features of society and economy with the biosphere and atmosphere into one modelling framework.

# Global Change Assessment Model(GCAM)

GCAM is a market equilibrium model with a global scope and operates from 1990 to 2100 in five-year time steps. It can be used to examine, for example, how changes in population, income, or technology cost might alter crop production, energy demand, and water withdrawals, or how changes in one region’s demand for energy affect energy, water, and land in other regions.

GCAM has been developed at Pacific Northwest National Laboratory for over 30 years and is now a freely available community model and documented online. The team at JGCRI is comprised of economists, engineers, energy experts, forest ecologists, agricultural scientists, and climate system scientists who develop the model and apply it to a range of science and policy questions. The team works closely with Earth system and ecosystem modelers to integrate the human decision components of GCAM into their analyses.

Source : [PNNL](https://gcims.pnnl.gov/modeling/gcam-global-change-analysis-model)


# This webpage is made with Quarto.

```{mermaid}
%%| label: fig-mermaid
%%| fig-width: 6
%%| fig-cap: |
%%|   How Quarto orchestrates rendering of documents: start with 
%%|   a qmd file, use the Knitr or Jupyter engine to perform the 
%%|   computations and convert it to an md file, then use Pandoc 
%%|   to convert to various file formats including HTML, PDF, 
%%|   and Word.
flowchart LR
  A[qmd] --> B(Knitr)
  A[qmd] --> C(Jupyter)
  B(Knitr) --> D[md]
  C(Jupyter) --> D[md]
  D[md] --> E(pandoc)
  E(pandoc) --> F(HTML)
  E(pandoc) --> G(PDF)
  E(pandoc) --> H(Word)
  E(pandoc) --> I{and more}
```